name: On Plugin Release

on:
  repository_dispatch:
    types: onPluginRelease

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for ad-m/github-push-action to push local changes
    name: Add Release To Repo
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: checkout code
        uses: actions/checkout@v2
      - name: add release to plugin repo
        run: |
          echo "Go run addPluginReleaseToRepo: $(go run .github/workflows/addPluginReleaseToRepo.go '${{ toJson(github.event.client_payload) }}')"
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add plugin release ${{ github.event.client_payload.released.id }} ${{ github.event.client_payload.released.releases[0].version }}" -a
      - name: push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
