name: On Plugin Release Create Tag

on:
  repository_dispatch:
    types: onPluginReleaseCreateTag

jobs:
  build:
    name: Create tag for private plugin release
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: checkout code
        uses: actions/checkout@v2
      - uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1.7.2
        id: "tag_create"
        with:
          tag: ${{github.event.client_payload.tag}}
          tag_exists_error: false
          message: "Latest release"
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.event.client_payload.tag}}
          release_name: Release ${{github.event.client_payload.tag}}
          draft: false
          prerelease: false
